### ISSUE TITLE
runtests is broken in Django 1.8

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/django-pandas#45]
`django.test.simple` was removed in 1.8

**Comment by Parbhat** [comment]
@chrisdev  To Upgrade to Django 1.8 we have to do two steps - 

- The module **django.test.simple** and the class **django.test.simple.DjangoTestSuiteRunner** are removed in django 1.8 so we have to use **django.test.runner.DiscoverRunner**

The code to be change in runtests.py as

    def runtests(*test_args):
       if not test_args:
            test_args = ['django_pandas']

       parent = os.path.dirname(os.path.abspath(__file__))
       sys.path.insert(0, parent)

       if django.VERSION < (1, 8):
          from django.test.simple import DjangoTestSuiteRunner
          failures = DjangoTestSuiteRunner(
          verbosity=1, interactive=True, failfast=False).run_tests(['tests'])
          sys.exit(failures)

       else:
          from django.test.runner import DiscoverRunner
          failures = DiscoverRunner(
            verbosity=1, interactive=True, failfast=False).run_tests(test_args)
          sys.exit(failures)

**django.test.runner.DiscoverRunner**  is introduced only in Django 1.6 so we have to check for version.
This works and remove the existing error *ImportError: No module named 'django.test.simple'*

- The Tests now run fine in Django 1.7.x but in Django 1.8, some tests fail with attribute errors which can be fixed by making tests files  compatible with django 1.8

**Comment by chrisdev** [comment]
Ok Is this all that is blocking 1.8 compatibility?
If this is the case maybe you can do a pull request?
Well done @Parbhat

**Comment by Parbhat** [comment]
yes @chrisdev

**Comment by Parbhat** [comment]
@chrisdev only one error is left specific to django 1.8, working to solve it

**Comment by chrisdev** [comment]
@Parbhat  this error is a consequence of https://code.djangoproject.com/ticket/24211
`qs.aggregate_names` changed to `qs.annotation_names`
ValuesQuerySet() and ValuesListQuerySet() have been replaced by ValuesIterator

**Comment by Parbhat** [comment]
@chrisdev Great so now django-pandas can be upgraded to 1.8

**Comment by chrisdev** [comment]
Test are failing because our travis.cl and fox config sucks. We've got to update and modernise

**Comment by chrisdev** [comment]
Created a issue #50 to create a better travis/tox config.
