### ISSUE TITLE
Get all fields in related model

### ISSUE THREAD

**Issue by rkpatel33** [chrisdev/django-pandas#73]
Is there a way to get all the fields in a related model instead of having to explicitly follow individual relationships with the double underscore notation (`'offer__provider'`)?

For example I have the following statement:

```
productapps = ProductApplication.objects.all().select_related('offer')
```

And I want to turn that queryset into a dataframe with all the fields from `ProductApplication` and `Offer`.

**Comment by pathway** [comment]
I have this same issue.  @chrisdev can you comment on this, why is it closed?  if we should solve this another way can you give us a hint?

**Comment by chrisdev** [comment]
I'm reopening @rkpatel33 :smile:

**Comment by pathway** [comment]
This is how I solved it myself, in case it is useful to you at all.

Given class Parent, and class Child with FK to Parent: 
```
cols=['childfield','parent__field']
fr = Child.objects.select_related('parent').values_list(*cols)
df=pd.DataFrame.from_records(data=list(fr),columns=cols )
```

- with this approach, I had to list cols manually
- values() did not work (it complained about not recognizing parent__field which I thought was very strange), I had to use values_list for some reason.  I did not realize values and values_list should act differently in this way?

**Comment by chrisdev** [comment]
So @pathway you think now that you could send us a PR?

**Comment by chrisdev** [comment]
@pathway this is open source 😄 after all. We  put it out there with the hope that people would use it read the source and hopefully contribute improvements, bug fixes and so on.  `djanog-pandas` is free to use and modify as you please.  Provided at no cost to you. You're are benefiting for the work of myself and many other contributors.  That's what I think @pathway

**Comment by pathway** [comment]
Yes I benefit from open source 100%, and am happy to contribute wherever reasonable!

However, no I have not benefited from this project at all yet, because it did not do what I needed, which is: Get fields in related model.  I provided my solution code above, "at no cost to you" as you say.

If I saw a simple way to integrate my solution code with this project, I may be willing to do so.  But at the moment, its simpler for me to just use the 3 lines above.  After briefly looking at this project's source code, its not clear to me that the approach I took in my 3 lines would be directly helpful.

Of course I wish you the best with this project!  Your goal is to connect two excellent open source frameworks which is awesome.
